#ifndef PIECE_ATTACK_MASKS_H
#define PIECE_ATTACK_MASKS_H

extern U64 BISHOP_LOOKUP_MASKS[BOARD_SQUARES];

extern U64 ROOK_LOOKUP_MASKS[BOARD_SQUARES];

extern U64 PAWN_LOOKUP_MASKS[2][BOARD_SQUARES];

extern U64 KNIGHT_LOOKUP_MASKS[BOARD_SQUARES];

extern U64 KING_LOOKUP_MASKS[BOARD_SQUARES];


extern int BISHOP_RELEVANT_BITS[BOARD_SQUARES];

extern int ROOK_RELEVANT_BITS[BOARD_SQUARES];

#endif // PIECE_ATTACK_MASKS_H